# Generated by Django 3.2.13 on 2022-06-14 20:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220614_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support_tickets',
            options={'verbose_name_plural': 'Supprt Tickets'},
        ),
        migrations.AlterModelOptions(
            name='tickets_messages',
            options={'verbose_name_plural': 'Support Responses'},
        ),
        migrations.AddField(
            model_name='support_tickets',
            name='query_image',
            field=cloudinary.models.CloudinaryField(default='url_placeholder', max_length=255, verbose_name='image'),
        ),
    ]
