# Generated by Django 3.2.13 on 2022-06-15 11:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220614_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support_tickets',
            options={'verbose_name_plural': 'Support Tickets'},
        ),
        migrations.RemoveField(
            model_name='support_tickets',
            name='query_image',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='profile_placeholder', max_length=255, verbose_name='Screenshot'),
        ),
    ]
