# Generated by Django 3.2.13 on 2022-04-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_profile_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='visible',
        ),
        migrations.AddField(
            model_name='url_links',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
