# Generated by Django 3.2.13 on 2022-06-12 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url_Clicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.url_links')),
            ],
        ),
    ]
