# Generated by Django 3.2.13 on 2022-06-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_url_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_links',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Url_Clicks',
        ),
    ]
