# Generated by Django 3.2.13 on 2022-06-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0008_support_messages_support_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support_ticket',
            options={'verbose_name_plural': 'Support Tickets'},
        ),
        migrations.AlterModelOptions(
            name='url_links',
            options={'verbose_name_plural': 'URL Links'},
        ),
        migrations.AlterField(
            model_name='support_ticket',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')], default=0),
        ),
    ]
