# Generated by Django 3.2.13 on 2022-06-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0009_auto_20220613_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support_ticket',
            name='user',
        ),
        migrations.DeleteModel(
            name='Support_Messages',
        ),
        migrations.DeleteModel(
            name='Support_Ticket',
        ),
    ]
